name: 'Telegram'
description: 'Bot de telegram'
inputs:
  who-to-greet: id
  description: 'Who to greet'
  required: true
  default: 'World'
outputs:
  time:
  description: 'time'
runs:
  using: 'node12'
  main: 'index.js'
