name: example_workflow
on: 
 push:
  branches:
    - react_app_deploy
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
      
    - name: Run Statics
      run: |
       cd react-app
       npm install
       npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: path/to/artifact/world.txt
      
  job2:
    runs-on: ubuntu-latest
    name: deploy 
    needs: job1
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: Deploy to foo-bar.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'foo-bar.surge.sh'
        project: '.'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
