name: send_telegram_workflow
on:
  push:
    branches:
      - send_telegram_action
jobs:
  job1:
    runs-on: ubuntu-latest
    name: envio_mensaje
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Telegram
        uses: ./index.js
        env:
          DEFAULT_BRANCH: send_telegram_action
      - name: Output
        run: echo "hola " 
      
